image: openjdk:8-jdk

stages:
  - Build
  - Test

setPermissions: # Set gradlew as executable to avoid 'Permission denied' failures
  stage: .pre
  script:
    - chmod -x gradlew

staticAnalysis:
  stage: Build
  script:
    - ./gradlew ktlintCheck
  rules: # Only on merge requests and commits to master
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_MERGE_REQUEST_ID

build:
  stage: Build
  script:
    - ./gradlew assemble

test:
  stage: Test
  script:
    - ./gradlew test